export const products = [
  {
    image: 'https://5.imimg.com/data5/BV/GW/ZJ/ANDROID-26211097/img-20200729-wa0039-jpg-500x500.jpg',
    productId: '1',
    productName: 'R S Enterprises Men Sweatshirt',
    productPrice: 299,
    productReview: '3.6',
    discountPrice: 50,
    quantity: 1,
  },
  {
    image: 'https://ae01.alicdn.com/kf/H20c8352b6ba54740b2883e7f6c53e2dac/Long-Sleeve-Men-s-Hoodies-Hood-Half-Black-Half-White-Cool-Plain-Hoddies-Men-Patchwork-Cotton.jpg',
    productId: '2',
    productName: 'ZOGAA Long Sleeve Mens Hoodie',
    productPrice: 399,
    productReview: '3.9',
    discountPrice: 40,
    quantity: 1,
  },
  {
    image: 'https://rlv.zcache.com/black_and_white_hoddy_hoodie-r44991d84f9774389b4e549d072d03e26_jg5ax_704.jpg',
    productId: '3',
    productName: 'Zazzle White hoodie',
    productPrice: 1999,
    productReview: '4.5',
    discountPrice: 100,
    quantity: 1,
  },
  {
    image: 'https://images-na.ssl-images-amazon.com/images/I/71TmZgVFbFL._UL1500_.jpg',
    productId: '4',
    productName: 'SV Style Printed Hoddie',
    productPrice: 699,
    productReview: '4.2',
    discountPrice: 150,
    quantity: 1,
  },
  {
    image: 'https://images-na.ssl-images-amazon.com/images/I/61DshtkZSKL._AC_UY445_.jpg',
    productId: '5',
    productName: 'FLYCHEN Mens Digital Print Sweatshirts',
    productPrice: 1999,
    productReview: '3.9',
    discountPrice: 500,
    quantity: 1,
  },
  {
    image: 'https://images-na.ssl-images-amazon.com/images/I/519xB5Lg98L._AC_UX342_.jpg',
    productId: '6',
    productName: 'GLUDEAR Unisex 3D Pattern Print Athletic Pullover Hoodies',
    productPrice: 2499,
    productReview: '4.5',
    discountPrice: 600,
    quantity: 1,
  },
  {
    image: 'https://images-na.ssl-images-amazon.com/images/I/61YE2shWkPL._UX569_.jpg',
    productId: '7',
    productName: 'Triumph Polyester Casual Thermal Hooded Hoodie',
    productPrice: 1699,
    productReview: '4.4',
    discountPrice: 700,
    quantity: 1,
  },
  {
    image: 'https://canary.contestimg.wish.com/api/webimage/5d733b925beeeb344ed42300-large.jpg?cache_buster=283462c40f9a131146c2ad1f64b63721',
    productId: '8',
    productName: ' Todoroki Shoto Cosplay Casual Hoodie',
    productPrice: 999,
    productReview: '4.0',
    discountPrice: 300,
    quantity: 1,
  },
  {
    image: 'https://images-na.ssl-images-amazon.com/images/I/51TT8BoCF2L._UX425_.jpg',
    productId: '9',
    productName: 'ADRO Marshmellow Printed Hoodie',
    productPrice: 799,
    productReview: '4.1',
    discountPrice: 200,
    quantity: 1,
  },
  {
    image: 'https://assets.adidas.com/images/w_600,f_auto,q_auto/a0809d4b25354abeaa5aa92901113e90_9366/Trefoil_Hoodie_White_DU7780_01_laydown.jpg',
    productId: '10',
    productName: 'Trefoil Hoddie - ADIDAS',
    productPrice: 3499,
    productReview: '4.5',
    discountPrice: 200,
    quantity: 1,
  },
  {
    image: 'https://www.dressinn.com/f/13719/137193244/nike-sportswear-club-graphic-hoodie-regular.jpg',
    productId: '11',
    productName: 'Nike Sportswear Club Hoodie',
    productPrice: 2999,
    discountPrice: 500,
    productReview: '4.7',
    discountPrice: 200,
    quantity: 1,
  },
  {
    image: 'https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/596097/02/fnd/IND/fmt/png/BMW-M-Motorsport-Hooded-Sweat-Jacket',
    productId: '12',
    productName: 'PUMA BMW Motorsport Hoodie',
    productPrice: 3999,
    discountPrice: 700,
    productReview: '4.8',
    discountPrice: 200,
    quantity: 1,
  },
]